### ISSUE TITLE
Update to allow newer LiveView?

### ISSUE THREAD

**Issue by dfalling** [BartOtten/phoenix_live_head#1]
Hi, thanks for creating this package!

I tried installing it, but it looks like it's pinned to a specific older version of LiveView. Are there technical reasons for this, or could the versioning be relaxed to permit later versions?

> Because every version of phoenix_live_favicon depends on phoenix_live_head ~> 0.1.0 which depends on phoenix_live_view ~> 0.17.0, phoenix_live_favicon requires phoenix_live_view ~> 0.17.0.
And because your app depends on phoenix_live_favicon ~> 0.1.0, phoenix_live_view ~> 0.17.0 is required.
So, because your app depends on phoenix_live_view ~> 0.18.3, version solving failed.

**Comment by BartOtten** [comment]
@dfalling Thanks for reporting this issue. The versioning was indeed too strict; have adjusted the deps so the project can be used in future versions of Phoenix.
